package com.myoffgridai.proactive.model;

/**
 * Categories for proactive insights generated by the AI engine.
 */
public enum InsightCategory {
    HOMESTEAD,
    HEALTH,
    RESOURCE,
    GENERAL
}
